name: flutter_barcode_scanner_validation
description: A fork of flutter_barcode_scanner adding validation functionality. A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.
version: 1.0.1
homepage: https://github.com/anthonyfromoregon/flutter_barcode_scanner_validation

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  plugin:
    platforms:
      android:
        package: com.amolg.flutterbarcodescanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: SwiftFlutterBarcodeScannerPlugin